### ISSUE TITLE
Not able to run the filter

### ISSUE THREAD

**Issue by AlexW0lf1** [pandocker/pandoc-docx-pagebreak-py#6]
System: Ubuntu 22.0.4
Installed package running command from the readme.md
When tried to run this command(from folder containing readme file):
`pandoc -f markdown -t docx -o docx.docx --filter=pandoc-docx-pagebreakpy README.md`
Got an error:
Error running filter pandoc-docx-pagebreakpy:
Could not find executable pandoc-docx-pagebreakpy

Should I specify executable file location somehow? Or can I install it manually and make executable?

**Comment by K4zuki** [comment]
@AlexW0lf1, Can you try:

- Uninstall the git-installed package and do either one:
    1. Install from pypi: `pip3 install pandoc-docx-pagebreak`
    1. Install from pypi **as root:** `sudo pip3 install pandoc-docx-pagebreak`

**Comment by AlexW0lf1** [comment]
Tried both, got same errors:

Traceback (most recent call last):
  File "/usr/local/bin/pandoc-docx-pagebreakpy", line 5, in <module>
    from docx_pagebreak import main
  File "/usr/local/lib/python3.10/dist-packages/docx_pagebreak/__init__.py", line 12, in <module>
    import panflute as pf
  File "/usr/local/lib/python3.10/dist-packages/panflute-1.6.4-py3.10.egg/panflute/__init__.py", line 9, in <module>
  File "/usr/local/lib/python3.10/dist-packages/panflute-1.6.4-py3.10.egg/panflute/containers.py", line 10, in <module>
ImportError: cannot import name 'MutableSequence' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
Error running filter pandoc-docx-pagebreakpy:
Filter returned error status 1

**Comment by AlexW0lf1** [comment]
Looks like it has something to do with collections.MutableSequence being removed from python 3.10
Maybe I need to try another version

**Comment by AlexW0lf1** [comment]
Reinstalled pandoc-docx-pagebreak

Pandoc version:
pandoc 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.2, skylighting 0.8.5

pandoc-docx-pagebreak  0.0.3.dev5+gc8cddcc (pip3 install git+https://github.com/pandocker/pandoc-docx-pagebreak-py)
panflute               2.3.1
PyYAML                 5.4.1

Error message:
 File "/home/alex/.local/lib/python3.10/site-packages/panflute/elements.py", line 66, in __init__
    raise TypeError("invalid api version", api_version)
TypeError: ('invalid api version', [1, 20])
Error running filter pandoc-docx-pagebreakpy:
Filter returned error status 1

Tried with

pandoc-docx-pagebreak  0.0.2 (Installed via pip3 install pandoc-docx-pagebreak)

Error message: (same)
File "/home/alex/.local/lib/python3.10/site-packages/panflute/elements.py", line 66, in __init__
    raise TypeError("invalid api version", api_version)
TypeError: ('invalid api version', [1, 20])
Error running filter pandoc-docx-pagebreakpy:
Filter returned error status 1

And with

pandoc-docx-pagebreak-0.0.2 (sudo pip3 install pandoc-docx-pagebreak)
Error message: same

Probably need to somehow update api version

**Comment by AlexW0lf1** [comment]
With pandoc 3.1.13 works as expected, so my problem was most likely related to unmatched versions of pandoc and panflute. Not tested with pandoc-docx-pagebreak 0.0.3.dev5+gc8cddcc though.

**Comment by AlexW0lf1** [comment]
With pandoc 3.1.13 works as expected (currently using pandoc-docx-pagebreak-0.0.2). My problem most likely was related to unmatched versions of pandoc and panflute.
